### ISSUE TITLE
Simple fcm client crashing on android

### ISSUE THREAD

**Issue by zasyadev** [evollu/react-native-fcm#1054]
Reproduce
  i. clone the project
  ii. npm install
  iii. react-native run-android

Expexted behaviour:
App should build successfully and launch

Current Behaviour
App build successfully but **crashes** before Launching

When openning an issue, please include following information for better support

1. What version of RN and react-native-fcm are you running?
  "react-native": "^0.55.4",
  "react-native-fcm": "^16.2.3",
  "react-native-maps": "^0.22.0"

2. What device are you using? (e.g iOS9 emulator, Android 6 device)?
  Android
3. Is your app running in foreground, background or not running?
  Not running

**app/build.gradle**

```
dependencies {
    compile(project(':react-native-maps')) {
        exclude group: 'com.google.android.gms', module: 'play-services-base'
        // exclude group: 'com.google.android.gms', module: 'play-services-maps'
        // This resolution make compiler ignoring play-service-base's version requirement in react-native-maps
        // so that it only read from react-native-fcm
        // you can also lock the version in this gradle file and ignore all module declaration
        // or you can use ResolutionStragety
    }
    compile project(':react-native-fcm')
    implementation "com.google.android.gms:play-services-base:15.0.1"
    implementation "com.google.firebase:firebase-core:15.0.1"
    implementation "com.google.firebase:firebase-messaging:15.0.1"
    compile fileTree(dir: "libs", include: ["*.jar"])
    implementation fileTree(dir: "libs", include: ["*.jar"])
    // implementation "com.android.support:appcompat-v7:26.0.1"
    // compile ('com.facebook.react:react-native:0.46.4') { force = true } // super hack! From node_modules
    compile ("com.facebook.react:react-native:+") { force = true } // From node_modules
}
```

**Some line from logcat**

```
10-22 15:47:21.659  5479  5509 I zygote  :   at com.facebook.react.bridge.NativeModuleRegistry com.facebook.react.ReactInstanceManager.processPackages(com.facebook.react.bridge.ReactApplicationContext, java.util.List, boolean) (ReactInstanceManager.java:1142)
10-22 15:47:21.659  5479  5509 I zygote  :   at com.facebook.react.bridge.ReactApplicationContext com.facebook.react.ReactInstanceManager.createReactContext(com.facebook.react.bridge.JavaScriptExecutor, com.facebook.react.bridge.JSBundleLoader) (ReactInstanceManager.java:1080)
10-22 15:47:21.659  5479  5509 I zygote  :   at com.facebook.react.bridge.ReactApplicationContext com.facebook.react.ReactInstanceManager.access$900(com.facebook.react.ReactInstanceManager, com.facebook.react.bridge.JavaScriptExecutor, com.facebook.react.bridge.JSBundleLoader) (ReactInstanceManager.java:113)
10-22 15:47:21.659  5479  5509 I zygote  :   at void com.facebook.react.ReactInstanceManager$5.run() (ReactInstanceManager.java:911)
10-22 15:47:21.659  5479  5509 I zygote  :   at void java.lang.Thread.run() (Thread.java:764)
10-22 15:47:21.659  5479  5509 I zygote  :
10-22 15:47:21.667  5479  5509 E AndroidRuntime: FATAL EXCEPTION: Thread-3
10-22 15:47:21.667  5479  5509 E AndroidRuntime: Process: com.google.firebase.quickstart.fcm, PID: 5479
10-22 15:47:21.667  5479  5509 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/maps/GoogleMapOptions;
10-22 15:47:21.667  5479  5509 E AndroidRuntime:        at com.airbnb.android.react.maps.AirMapManager.<init>(AirMapManager.java:58)
10-22 15:47:21.667  5479  5509 E AndroidRuntime:        at com.airbnb.android.react.maps.MapsPackage.createViewManagers(MapsPackage.java:39)
10-22 15:47:21.667  5479  5509 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:756)
10-22 15:47:21.667  5479  5509 E AndroidRuntime:        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:173)
10-22 15:47:21.667  5479  5509 E AndroidRuntime:        at com.facebook.react.CoreModulesPackage.access$200(CoreModulesPackage.java:53)
10-22 15:47:21.667  5479  5509 E AndroidRuntime:        at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:130)
10-22 15:47:21.667  5479  5509 E AndroidRuntime:        at com.facebook.react.CoreModulesPackage$7.get(CoreModulesPackage.java:127)
10-22 15:47:21.667  5479  5509 E AndroidRuntime:        at com.facebook.react.LazyReactPackage.createNativeModules(LazyReactPackage.java:79)
10-22 15:47:21.667  5479  5509 E AndroidRuntime:        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:106)
10-22 15:47:21.667  5479  5509 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1172)
10-22 15:47:21.667  5479  5509 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1142)
10-22 15:47:21.667  5479  5509 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1080)
10-22 15:47:21.667  5479  5509 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:113)
10-22 15:47:21.667  5479  5509 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:911)
10-22 15:47:21.667  5479  5509 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
10-22 15:47:21.667  5479  5509 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.google.android.gms.maps.GoogleMapOptions
10-22 15:47:21.667  5479  5509 E AndroidRuntime:        at java.lang.VMClassLoader.findLoadedClass(Native Method)
10-22 15:47:21.667  5479  5509 E AndroidRuntime:        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
10-22 15:47:21.667  5479  5509 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
10-22 15:47:21.667  5479  5509 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
10-22 15:47:21.667  5479  5509 E AndroidRuntime:        ... 15 more
10-22 15:47:21.667  5479  5509 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/safeparcel/zza;
10-22 15:47:21.667  5479  5509 E AndroidRuntime:        ... 15 more
10-22 15:47:21.667  5479  5509 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.zza" on path: DexPathList[[zip file "/data/app/com.google.firebase.quickstart.fcm-qWRW9Q7Jx5OwAagR1o3-4A==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.firebase.quickstart.fcm-qWRW9Q7Jx5OwAagR1o3-4A==/lib/arm, /data/app/com.google.firebase.quickstart.fcm-qWRW9Q7Jx5OwAagR1o3-4A==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
10-22 15:47:21.667  5479  5509 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
10-22 15:47:21.667  5479  5509 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
10-22 15:47:21.667  5479  5509 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
10-22 15:47:21.667  5479  5509 E AndroidRuntime:        ... 15 more
10-22 15:47:21.673  5479  5516 I Adreno  : QUALCOMM build                   : 7f08991, I8a9bdcf8d3
10-22 15:47:21.673  5479  5516 I Adreno  : Build Date                       : 12/21/17
10-22 15:47:21.673  5479  5516 I Adreno  : OpenGL ES Shader Compiler Version: EV031.20.00.04
10-22 15:47:21.673  5479  5516 I Adreno  : Local Branch                     :
10-22 15:47:21.673  5479  5516 I Adreno  : Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.6.5.R1.08.00.00.312.040
10-22 15:47:21.673  5479  5516 I Adreno  : Remote Branch                    : NONE
10-22 15:47:21.673  5479  5516 I Adreno  : Reconstruct Branch               : NOTHING
10-22 15:47:21.674  5479  5516 I vndksupport: sphal namespace is not configured for this process. Loading /vendor/lib/hw/gralloc.msm8953.so from the current namespace instead.
10-22 15:47:21.686  1435  2124 W ActivityManager:   Force finishing activity com.google.firebase.quickstart.fcm/.MainActivity
10-22 15:47:21.689  1435  2124 D ActivityTrigger: ActivityTrigger activityPauseTrigger
10-22 15:47:21.693  1435  1537 I ActivityManager: Showing crash dialog for package com.google.firebase.quickstart.fcm u0
10-22 15:47:21.695  5479  5516 I Adreno  : PFP: 0x005ff087, ME: 0x005ff063
10-22 15:47:21.703  3087  5113 I Icing   : Indexing done com.google.android.apps.messaging-internal.3p:Person_no_gsa
10-22 15:47:21.704  5479  5516 I OpenGLRenderer: Initialized EGL, version 1.4
10-22 15:47:21.704  3087  5113 I Icing   : Indexing com.google.android.apps.messaging-internal.3p:Conversation_no_gsa from com.google.android.apps.messaging
```

**Comment by abdurrahmanekr** [comment]
I have this problem too
