### ISSUE TITLE
Crash on first startup

### ISSUE THREAD

**Issue by Desintegrator** [evollu/react-native-fcm#1139]
Had crash on each first app load with this crashlogs:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: my.app.id, PID: 28780
    java.lang.RuntimeException: Unable to instantiate service com.evollu.react.fcm.MessagingService: java.lang.ClassNotFoundException: Didn't find class "com.evollu.react.fcm.MessagingService" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/my.app.id-_dssBPggaaPYTtkmDU0T4Q==/base.apk"],nativeLibraryDirectories=[/data/app/my.app.id-_dssBPggaaPYTtkmDU0T4Q==/lib/arm64, /data/app/my.app.id-_dssBPggaaPYTtkmDU0T4Q==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4136)
        at android.app.ActivityThread.access$2400(ActivityThread.java:273)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2055)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.evollu.react.fcm.MessagingService" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/my.app.id-_dssBPggaaPYTtkmDU0T4Q==/base.apk"],nativeLibraryDirectories=[/data/app/my.app.id-_dssBPggaaPYTtkmDU0T4Q==/lib/arm64, /data/app/my.app.id-_dssBPggaaPYTtkmDU0T4Q==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:103)
        at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:1)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4131)
        at android.app.ActivityThread.access$2400(ActivityThread.java:273) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2055) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
    	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/messaging/FirebaseMessagingService;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        		... 12 more
     Caused by: java.lang.ClassNotFoundException: com.google.firebase.messaging.FirebaseMessagingService
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        		... 15 more
     Caused by: java.lang.IllegalAccessError: Class com.google.firebase.iid.zzc extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in /data/app/my.app.id-_dssBPggaaPYTtkmDU0T4Q==/base.apk!classes2.dex)
        		... 15 more
```

**Comment by Desintegrator** [comment]
Fix it with such changes in react-native-fcm build.gradle config:

```
def DEFAULT_COMPILE_SDK_VERSION             = 29
def DEFAULT_BUILD_TOOLS_VERSION             = "29.0.0"
def DEFAULT_TARGET_SDK_VERSION              = 29
def DEFAULT_FIREBASE_CORE_VERSION           = "17.5.0"
def DEFAULT_FIREBASE_MESSAGING_VERSION      = "20.2.4"
```
