### ISSUE TITLE
Attempt to call JS function before JS bundle is loaded.

### ISSUE THREAD

**Issue by atlanteh** [evollu/react-native-fcm#192]
Please include following information for better support

What verion of RN and react-native-fcm are you running?
**RN: 0.36.0**
**react-native-fcm: 2.3.2**

What device are you using? (e.g iOS9 emulator, Android 6 device)?
**Android** (failed in Crashlytics - not sure which android)

Is your app running in foreground, background or not running?
**On first load**

We received the following errror:
```java
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=com.evollu.react.fcm.FCMRefreshToken flg=0x10 (has extras) } in com.evollu.react.fcm.FIRMessagingModule$1@42eb0978
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:782)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5579)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.RuntimeException: Attempt to call JS function before JS bundle is loaded.
       at com.facebook.react.cxxbridge.CatalystInstanceImpl.callFunction(CatalystInstanceImpl.java:199)
       at com.facebook.react.bridge.JavaScriptModuleRegistry$JavaScriptModuleInvocationHandler.invoke(JavaScriptModuleRegistry.java:110)
       at $Proxy3.emit(Unknown Source)
       at com.evollu.react.fcm.FIRMessagingModule.sendEvent(FIRMessagingModule.java:118)
       at com.evollu.react.fcm.FIRMessagingModule.access$100(FIRMessagingModule.java:35)
       at com.evollu.react.fcm.FIRMessagingModule$1.onReceive(FIRMessagingModule.java:129)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:772)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5579)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)

``

**Comment by evollu** [comment]
taking look at this.

**Comment by evollu** [comment]
seems to be fixed https://github.com/facebook/react-native/commit/68aeffe01f442a67a53dd0eff43e9357b0ac3b22

**Comment by evollu** [comment]
reopen if you see this again
