### ISSUE TITLE
android crash - runtime exception when trying to run app first time

### ISSUE THREAD

**Issue by zoharlevin** [evollu/react-native-fcm#257]
i'm trying to add react-native-fcm to my app which already had some push notification handling in native code (google play-services were there already). 

so after getting the gradle build to pass successfully i tried running the app first time (without any code to handle the notifications yet) and i'm getting this crash as soon as the app starts:

```
FATAL EXCEPTION: main
java.lang.NoSuchMethodError: No static method isDeviceProtectedStorage(Landroid/content/Context;)Z in class Landroid/support/v4/content/ContextCompat; or its super classes (declaration of 'android.support.v4.content.ContextCompat' appears in 
          at com.google.firebase.FirebaseApp.zza(Unknown Source)
          at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
          at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
          at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
          at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
          at android.content.ContentProvider.attachInfo(ContentProvider.java:1789)
          at android.content.ContentProvider.attachInfo(ContentProvider.java:1764)
          at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
          at android.app.ActivityThread.installProvider(ActivityThread.java:6767)
          at android.app.ActivityThread.installContentProviders(ActivityThread.java:6362)
          at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6302)
          at android.app.ActivityThread.access$1800(ActivityThread.java:222)
          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1861)
          at android.os.Handler.dispatchMessage(Handler.java:102)
          at android.os.Looper.loop(Looper.java:158)
          at android.app.ActivityThread.main(ActivityThread.java:7229)
          at java.lang.reflect.Method.invoke(Native Method)
          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

after some research it seemed like the crash should somehow be related to different packages depending on different versions of firebase SDK but i looked at all my app dependencies and they seem to be consistent.

any suggestions as to how i can solve this?

**my environment:**

react-native 0.36.0
react-native-fcm 2.5.5
device Samsung Galaxy S7

in my app/build.gradle: 
```
dependencies { 

   ...
   compile 'com.android.support:support-v4:23.1.1'
   compile 'com.android.support:appcompat-v7:23.0.1'
   ...
   compile 'com.google.firebase:firebase-core:10.0.1'
   compile 'com.google.firebase:firebase-crash:10.0.1'
   ...
   compile 'com.google.android.gms:play-services-gcm:10.0.1'
   compile 'com.google.android.gms:play-services-location:10.0.1'
}
```
and at the bottom of the file:
``` apply plugin: 'com.google.gms.google-services' ```

in my android/build.gradle:
```
classpath 'com.google.gms:google-services:3.0.0'
```

**Comment by zoharlevin** [comment]
the reason for my crash was that firebase-core depended on com.android.support:support-v4:24.0.0 . looks like the minimum android API to use here is 24.

**Comment by lutfianasari** [comment]
I'm sorry to ask.
So, do you change your minimum android API to 24?
And does it mean we wouldn't solve the error if we want to make the app work on API below 24?

**Comment by nicks258** [comment]
I am using 26 still i am getting this fatal crash.

**Comment by evollu** [comment]
sounds like a firebase team quesiton

**Comment by NehaKushwah993** [comment]
I am also getting same error

**Comment by NehaKushwah993** [comment]
did you find solution?

**Comment by NZQiu** [comment]
Got same error.
Change the following details it will work fine.

compileSdkVersion 26
