### ISSUE TITLE
Android REMOTE large_icon not working with local notification

### ISSUE THREAD

**Issue by abbasfreestyle** [evollu/react-native-fcm#284]
When i try to receive the large_icon via https, local notification fails.

i use my local notification like so:

```
sendNotify(){
    FCM.scheduleLocalNotification({
        fire_date: new Date().getTime(),
        repeat_interval: "minute",
        id: "unique_id",
        title: "My App",
        body: data.title,
        sound: "default",
        priority: "high",
        large_icon: data.image,
        icon: "ic_launcher",
        show_in_foreground: true,
        big_text: data.message,
    });
  }
```

Logcat produces this error, it seems as though there's a permission issue accessing the internet:

```
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: failed to send local notification
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: android.os.NetworkOnMainThreadException
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1273)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at java.net.InetAddress.lookupHostByName(InetAddress.java:431)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at java.net.InetAddress.getAllByName(InetAddress.java:215)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at com.android.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:220)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:176)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:108)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at com.android.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:482)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:465)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:447)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:353)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:476)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:118)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:25)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at com.evollu.react.fcm.FIRLocalMessagingHelper.getBitmapFromURL(FIRLocalMessagingHelper.java:332)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at com.evollu.react.fcm.FIRLocalMessagingHelper.sendNotification(FIRLocalMessagingHelper.java:118)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at com.evollu.react.fcm.FIRLocalMessagingPublisher.onReceive(FIRLocalMessagingPublisher.java:12)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3635)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at android.app.ActivityThread.access$2000(ActivityThread.java:222)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1877)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at android.os.Looper.loop(Looper.java:158)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at android.app.ActivityThread.main(ActivityThread.java:7229)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at java.lang.reflect.Method.invoke(Native Method)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
01-25 19:12:16.387  5423  5423 E FIRLocalMessagingHelper: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

I already have this in my android manifest:
`<uses-permission android:name="android.permission.INTERNET" />`

When i change large_icon back to `large_icon: "ic_launcher"`, then local notification works like normal and the large icon displays.

Unforutnately my java skills are not good otherwise i wouldn't mind submitting a PR for this. Perhaps someone can help?

i've found this, maybe this could be of any use?
[http://stackoverflow.com/questions/6343166/how-to-fix-android-os-networkonmainthreadexception?page=1&tab=votes#tab-top](url)

What verion of RN and react-native-fcm are you running? **0.39 and react-native-fcm v2.5.6**
What device are you using? (e.g iOS9 emulator, Android 6 device)? **Android 6.0 real device**
Is your app running in foreground, background or not running? **both foreground and background**

**Comment by zorosun** [comment]
How did you solve this problem @abbasfreestyle ? Your `data.image` is  the actual image data right?
