### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by pgonzalez-santiago** [evollu/react-native-fcm#367]
Please include following information for better support

RN: 0.42.0 
react-native-fcm: Last version
Android 7.0 device
Application: not running

Every time I trie to run the App in the device I'm getting this error, do you have any ideas?

`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: de.perico.webpericoApp.alpha, PID: 5007
                  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzam;
                      at com.google.firebase.FirebaseOptions.fromResource(Unknown Source)
                      at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
                      at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
                      at android.content.ContentProvider.attachInfo(ContentProvider.java:1751)
                      at android.content.ContentProvider.attachInfo(ContentProvider.java:1726)
                      at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                      at android.app.ActivityThread.installProvider(ActivityThread.java:5811)
                      at android.app.ActivityThread.installContentProviders(ActivityThread.java:5403)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5342)
                      at android.app.ActivityThread.-wrap2(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzam" on path: DexPathList[[dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-support-annotations-24.0.0_a8cf4446fd5a0a3b2a66a85db56646b0515bd314-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-staticlayout-proxy-1.0_74abd7eea629e9b43041c2bd3be384c72126a23b-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-okio-1.9.0_0cf1701cdceb7ca3fbfb7f6674cb88c664d9de70-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-okhttp-ws-3.4.1_3a202ec70c8d08c534b1b25a889da781b7230a10-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-okhttp-urlconnection-3.4.1_351fd1af2a8d3f777334696fd45928a0c2a3eda0-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-okhttp-3.4.1_362028eb038a7deb98156c8038b31079fe162541-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-net.hockeyapp.android-HockeySDK-4.0.0_0a5ba57e370aecaf6cfc1a73fedb2088c081894e-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-me.relex-photodraweeview-1.0.0_d0a36171277cef1b89b282ca98e5c766ca2a2673-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-me.leolin-ShortcutBadger-1.1.10_e80188ea3e43a81333adf4f3fecab6929e683858-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-library-2.4.0_aadf6c056062a3046980f7bb1ed6f625ae0bf598-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-jsr305-3.0.0_b0e2d8dd58dd8671368c97564fc1d9bdb6c31bea-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-javax.inject-1_854c50b5779fac2f73573b1e7b518a5e21060852-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-internal_impl-24.0.0_22b6ec05377a29d27839f10297a5d7bbf3eea3ba-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-infer-annotations-1.5_f25712f1c742a374c5130cd03783e1772a0a0a22-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-com.yqritc-android-scalablevideoview-1.0.1_ca2763b365f54f610c4a91b793906015242f0a29-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-com.google.firebase-firebase-messaging-10.2.1_ede340186a9d24b705c73c8e0d0480db4d04b37d-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-com.google.firebase-firebase-iid-10.2.1_63330e0c11eaa7edfc50d8fe8266b39cd85
E/AndroidRuntime: 1983f-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-com.google.firebase-firebase-common-10.2.1_ec541fbe92b0f0e59a3e0ffb55c2a013c02c40b7-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-com.google.firebase-firebase-analytics-impl-10.2.1_c1dff53f321eca871b1c611ccedaf767075b084b-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-com.google.firebase-firebase-analytics-10.2.1_8123915520fa422c4860e671d4fe08e7c8c45464-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-com.google.android.gms-play-services-tasks-9.6.1_dc82897022053d43a9e65059e9d09cbcedd8dd15-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-com.google.android.gms-play-services-basement-9.6.1_a8663dbfac2b2772c0338ef6096b56355213adb7-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-com.google.android.gms-play-services-base-9.6.1_9344423612cc9c22d098312c90f34fc41da302f6-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-com.google.android.gms-play-services-analytics-impl-9.6.1_6f51b803b0a9347cc0afa23081e5c077fd92e88f-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-com.google.android.gms-play-services-analytics-9.6.1_4b9db9cca6dba5b924c4c85194d209e25ac9a927-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-com.facebook.soloader-soloader-0.1.0_38945eb2d0710205a3f9d8d53c82db66709afeb9-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-com.facebook.react-react-native-0.42.0_3a3361fc2826636c21fd79b1e6818d3237f44cb4-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-com.facebook.fresco-imagepipeline-okhttp3-0.11.0_84d339e851789fd801d7a411e263e69ae910b424-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-com.facebook.fresco-imagepipeline-base-0.11.0_bc718921c0e8ce1ab59761d549131cbe7c62425c-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-com.facebook.fresco-imagepipeline-0.11.0_90826775654327db6433b27dbccc039f22f0ad10-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-com.facebook.fresco-fresco-0.11.0_376e12aa3c31fa5a44e9aab64815563fb9e7b506-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-com.facebook.fresco-fbcore-0.11.0_ab2d2a55490805748f30e2fff6e2c3190a71d456-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-com.facebook.fresco-drawee-0.11.0_bc699310b73d9b988c9944d8862c14670a0ea7a2-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-com.facebook.fbui.textlayoutbuilder-textlayoutbuilder-1.0.0_dd94481b2c7e37b87ff94e0daab17f23832cf473-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-com.android.support-support-v4-24.0.0_85fccd452ce3742714a19c5f8f7d0a446e8b424a-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-com.android.support-recyclerview-v7-23.4.0_e12817b5d9367498270339df37c7c06946cb2a91-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-com.android.support-multidex-1.0.1_b42603ce4a7112959905c2a402b5e7cf669ee163-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-com.android.support-appcompat-v7-23.0.1_53eeeba029784fb77cf3a51bbdbf95c3fd4c9baf-classes.dex", dex file "/data/data/de.perico.webpericoApp.alpha/files/instant-run/dex/slice-bolts-tasks-1.4.0_378da
E/AndroidRuntime: 05a74f3be68e12bb68042566ba970db1dea-classes.dex"],nativeLibraryDirectories=[/data/app/de.perico.webpericoApp.alpha-1/lib/arm, /system/fake-libs, /data/app/de.perico.webpericoApp.alpha-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader.findClass(IncrementalClassLoader.java:90)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      	... 17 more`

**Comment by evollu** [comment]
not sure. Does it work on emulators?

**Comment by juboba** [comment]
Same error here. Any suggestions? Did you fix it?

**Comment by pgonzalez-santiago** [comment]
@juboba Nope, still have the problem. Have no idea how to fix it. :(

@evollu Yes, I am trying to run the app in the simulator. Android 6.0.0 with API 23.

**Comment by evollu** [comment]
try update your firebase version?
or turn off proguard?

**Comment by renielDev** [comment]
Im having the same problem. :(

**Comment by herarya** [comment]
+1 same issue
