### ISSUE TITLE
Error receiving broadcast Intent 

### ISSUE THREAD

**Issue by Sh3rawi** [evollu/react-native-fcm#417]
Hello,
We're seeing the below crash on android, the percentage of users affected by it is very small, but it happens alot to them (compared to their count).
RN version: 0.42.0
react-native-fcm version: 6.1.0

Crashlytics info:
- App in focus : %8
- Android Versions affected: 100% Android 7

Log: 
```
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=com.evollu.react.fcm.ReceiveNotification flg=0x10 launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } bqHint=1 (has extras) } in com.lbe.doubleagent.client.g$f@52c6306
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1195)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.messaging.RemoteMessage$Notification com.google.firebase.messaging.RemoteMessage.getNotification()' on a null object reference
       at com.evollu.react.fcm.FIRMessagingModule$2.onReceive(FIRMessagingModule.java:200)
       at com.lbe.doubleagent.client.a.onReceive(BroadcastReceiverDelegate.java:46)
       at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1185)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```
For some reason, message is null, and so (message.getNotification() != null) crashes
```
RemoteMessage message = intent.getParcelableExtra("data");
...
if (message.getNotification() != null) {
...
}
```

**Comment by evollu** [comment]
I wonder if it has to do with Firebase SDK if it only happens to android 7

**Comment by IgorGanapolsky** [comment]
This happens on android 7 on Samsung Galaxy S8.  Do you know what the reason is?
