### ISSUE TITLE
Android build is crashing when notification is received.

### ISSUE THREAD

**Issue by tomislavHonig** [evollu/react-native-fcm#585]
This is is log of the error that i get:

```
java.lang.NullPointerException: 
Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
                                                                          at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:74)
                                                                          at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
                                                                          at com.evollu.react.fcm.MessagingService$1.run(MessagingService.java:40)
                                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:173)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6459)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
```

React native version : 0.48.4
Android version : 7.0 (HTC 10)
react-native-fcm:9.7.0

**Comment by tomislavHonig** [comment]
It was a problem with react-native-navigation and some custom java coe in my MainApplication

**Comment by evollu** [comment]
cool

**Comment by lulzimfazlija** [comment]
@tomislavHonig How did you manage to fix it?

**Comment by lulzimfazlija** [comment]
@evollu since when the issues are being closed without any exponation on how to fix the issue? I think would have been better if first someone shows a way how to fix the problem then close the issue, this way it is not helpful at all for anyone!
