### ISSUE TITLE
Android: Could not invoke RNFIRMessaging.unsubscribeFromTopic

### ISSUE THREAD

**Issue by coreform** [evollu/react-native-fcm#621]
This occurs after force-closing and restarting the app and then subsequently making calls to subscribeToTopic (or unsubscribeFromTopic). The app redboxes then crashes completely (closes) most times.

![screenshot_20171020-113457_1024](https://user-images.githubusercontent.com/349139/31868383-e0d8b51a-b7e9-11e7-88c8-bac11466358d.png)

Sony Z5 Compact running Android 7.1.1
react-native-fcm 10.0.2
react-native 0.48.4

**Comment by evollu** [comment]
can you show a screenshot?

**Comment by coreform** [comment]
added screenshot

**Comment by evollu** [comment]
so the error is shown in the 3rd paragraph. The system can't allocate enough memory because you only have 15kb left. Are you seeing this all the time?

**Comment by coreform** [comment]
This occurs consistently after force closing (and restarting) the app.

My use-case is a resubscription mechanism which subscribes to one topic while unsubscribing from a range of other topics upon an in-app setting change, so FCM.unsubscribe is called potentially hundreds of times in a loop. That is fine until the app is force closed (and restarted), pretty soon the app will crash with this kind of exception:

```
12-05 18:47:47.301 9672-9714/? E/unknown:ReactNative: Exception in native call
                                                      java.lang.RuntimeException: Could not invoke RNFIRMessaging.unsubscribeFromTopic
                                                          at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:385)
                                                          at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
                                                          at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                          at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                          at android.os.Looper.loop(Looper.java:241)
                                                          at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                          at java.lang.Thread.run(Thread.java:761)
                                                       Caused by: java.lang.reflect.InvocationTargetException
                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                          at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
                                                          at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162) 
                                                          at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                          at android.os.Handler.handleCallback(Handler.java:751) 
                                                          at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                          at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                          at android.os.Looper.loop(Looper.java:241) 
                                                          at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194) 
                                                          at java.lang.Thread.run(Thread.java:761) 
                                                       Caused by: java.lang.OutOfMemoryError: Failed to allocate a 381608 byte allocation with 19160 free bytes and 18KB until OOM
                                                          at java.lang.StringBuilder.toString(StringBuilder.java:408)
                                                          at com.google.firebase.iid.zzk.zzhf(Unknown Source)
                                                          at com.google.firebase.iid.FirebaseInstanceId.zzhf(Unknown Source)
                                                          at com.google.firebase.messaging.FirebaseMessaging.unsubscribeFromTopic(Unknown Source)
                                                          at com.evollu.react.fcm.FIRMessagingModule.unsubscribeFromTopic(FIRMessagingModule.java:138)
                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                          at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374) 
                                                          at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162) 
                                                          at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                          at android.os.Handler.handleCallback(Handler.java:751) 
                                                          at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                          at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) 
                                                          at android.os.Looper.loop(Looper.java:241) 
                                                          at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194) 
                                                          at java.lang.Thread.run(Thread.java:761) 
```

**Comment by evollu** [comment]
`Caused by: java.lang.OutOfMemoryError: Failed to allocate a 381608 byte allocation with 19160 free bytes and 18KB until OOM`
