### ISSUE TITLE
[Android] App crashes on sending RemoteNotification

### ISSUE THREAD

**Issue by GrishmaM** [evollu/react-native-fcm#697]
i'm using
react-native---->>>> 0.50.3
react-native-fcm ---->>>  ^10.0.3
running the project on  Android 7 device

any help ?

**Comment by TranHanHieu** [comment]
me too,

**Comment by evollu** [comment]
any log?

**Comment by dooboolab** [comment]
Me too. Below are logs. It happends when app is only in foreground. background is fine.

12-21 14:39:46.129 5663-6910/com.my.app W/unknown:ReactNative: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
12-21 14:39:46.129 5663-6910/com.my.app W/MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {663ab8c} sending message to a Handler on a dead thread
                                                           java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {663ab8c} sending message to a Handler on a dead thread
                                                               at android.os.MessageQueue.enqueueMessage(MessageQueue.java:545)
                                                               at android.os.Handler.enqueueMessage(Handler.java:662)
                                                               at android.os.Handler.sendMessageAtTime(Handler.java:631)
                                                               at android.os.Handler.sendMessageDelayed(Handler.java:601)
                                                               at android.os.Handler.post(Handler.java:357)
                                                               at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:61)
                                                               at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                               at android.os.Handler.handleCallback(Handler.java:790)
                                                               at android.os.Handler.dispatchMessage(Handler.java:99)
                                                               at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                               at android.os.Looper.loop(Looper.java:164)
                                                               at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                               at java.lang.Thread.run(Thread.java:764)

**Comment by evollu** [comment]
are you building the app using expo?

**Comment by dooboolab** [comment]
@evollu 
Yes I am using expo.

**Comment by evollu** [comment]
then it is dup of #511

**Comment by GrishmaM** [comment]
I am not using expo, even im facing the same

**Comment by evollu** [comment]
@GrishmaM post your crash log

**Comment by lulzimfazlija** [comment]
@evollu I will post crash logs for @GrishmaM , probably he has the same issue as mine.

The crash log is as below:
java.lang.ClassCastException: x.y.z.MainApplication cannot be cast to com.facebook.react.ReactApplication
                                                                         at com.evollu.react.fcm.MessagingService$1.run(MessagingService.java:41)
                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

I have seen you have discussed this issue with plenty of people but idk if u were able to solve this?

**Comment by evollu** [comment]
@lulzimfazlija the conversion failed
check this line https://github.com/evollu/react-native-fcm/blob/master/Examples/simple-fcm-client/android/app/src/main/java/com/google/firebase/quickstart/fcm/MainApplication.java#L16
