### ISSUE TITLE
Compatibility with react-native-maps?

### ISSUE THREAD

**Issue by malinthe** [evollu/react-native-fcm#73]
I'm trying to build for android but it's failing with the following error at dexDebug:

```
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/actions/ItemListIntents;
Unknown source file : 	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file : 	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file : 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file : 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file : 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file : 	at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file : 	at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file : 	at com.android.dx.command.Main.main(Main.java:106)
```

I'm wondering if this is caused by react-native-maps since it uses some google libraries. The build.gradle file for react-native-maps mentions this:

```
dependencies {
  compile 'com.facebook.react:react-native:+'
  compile "com.google.android.gms:play-services-base:8.4.0"
  compile 'com.google.android.gms:play-services-maps:8.4.0'
}
```

Could this be causing some sort of a conflict? Any idea on how to get this sorted out?

**Comment by evollu** [comment]
can you ask them to upgrade to use purely +? play-service is 9.2.1 now and they are still sticking with 8

**Comment by malinthe** [comment]
@evollu I manually edited their gradle file and put + and it finally builds without any errors.

```
dependencies {
  compile 'com.facebook.react:react-native:+'
  compile "com.google.android.gms:play-services-base:+"
  compile 'com.google.android.gms:play-services-maps:+'
}
```
