### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by andfs** [evollu/react-native-fcm#82]
I'm using RN 0.30 and I have react-native-maps.
Always get this error:

Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/measurement/AppMeasurementContentProvider;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/measurement/AppMeasurementContentProvider;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)
    
:app:transformClassesWithDexForDebug FAILED

Can anyone help me?

**Comment by savioseb** [comment]
Try 3 things:

1. Delete /android/build
2. Delete /android/app/build
3. In the terminal:

```
$ cd android
$ ./gradlew clean
```

**Comment by andfs** [comment]
There was a conflict with react-native-card-scan. I resolve this issue by removing the line: 
`compile 'com.google.android.gms:play-services-gcm:8.4.0'`
from android/build.gradle of react-native-card-scan
