### ISSUE TITLE
Android 8.1.0 API 27 Crash: No virtual method setChannelId

### ISSUE THREAD

**Issue by maggialejandro** [evollu/react-native-fcm#820]
My app is crashing as soon as I open it.
Android: 8.1.0 API 27

```bash

FATAL EXCEPTION: GoogleApiHandler
Process: com.my.app, PID: 5987
java.lang.NoSuchMethodError: No virtual method setChannelId(Ljava/lang/String;)Landroid/support/v4/app/NotificationCompat$Builder; in class Landroid/support/v4/app/NotificationCompat$Builder; or its super classes (declaration of 'android.support.v4.app.NotificationCompat$Builder' appears in /data/app/com.my.app-u6HgsMCaTY-ls9z3O5LJiQ==/base.apk)
	at com.google.android.gms.common.GoogleApiAvailability.zza(Unknown Source:225)
	at com.google.android.gms.common.GoogleApiAvailability.zza(Unknown Source:15)
	at com.google.android.gms.common.api.internal.zzbm.zzc(Unknown Source:4)
	at com.google.android.gms.common.api.internal.zzbo.onConnectionFailed(Unknown Source:104)
	at com.google.android.gms.common.api.internal.zzbo.connect(Unknown Source:83)
	at com.google.android.gms.common.api.internal.zzbo.zza(Unknown Source:47)
	at com.google.android.gms.common.api.internal.zzbm.handleMessage(Unknown Source:283)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```

"react-native-fcm": "^13.3.3"

classpath 'com.google.gms:google-services:3.1.2'

'com.google.firebase:firebase-core:11.8.0'
'com.google.firebase:firebase-messaging:11.8.0'
'com.google.android.gms:play-services-gcm:11.8.0'

any ideas?

**Comment by maggialejandro** [comment]
It works by downgrading android dependencies to 11.6.0

**Comment by evollu** [comment]
possibly SDK required a function. however we don't use `setChannelId` at all. could a library sync issue
