### ISSUE TITLE
undefined is not an object (evaluating '_reactNativeFcm.NotificationActionType.TextInput') 

### ISSUE THREAD

**Issue by shrutiWV** [evollu/react-native-fcm#821]
While using this library i get following error please help!!

undefined is not an object (evaluating '_reactNativeFcm.NotificationActionType.TextInput')
Module AppRegistry is not a registered callable module (calling runApplication)

FATAL EXCEPTION: main
                                                                 Process: com.coupanreact, PID: 21083
                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
                                                                     at java.io.File.fixSlashes(File.java:185)
                                                                     at java.io.File.<init>(File.java:134)
                                                                     at com.facebook.react.devsupport.StackTraceHelper$StackFrameImpl.<init>(StackTraceHelper.java:43)
                                                                     at com.facebook.react.devsupport.StackTraceHelper$StackFrameImpl.<init>(StackTraceHelper.java:31)
                                                                     at com.facebook.react.devsupport.StackTraceHelper.convertJsStackTrace(StackTraceHelper.java:115)
                                                                     at com.facebook.react.devsupport.DevSupportManagerImpl$3.run(DevSupportManagerImpl.java:294)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5257)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)

i amusing versions:-
react-native-cli: 2.0.1
react-native: 0.44.0

**Comment by evollu** [comment]
what is your react-native-fcm version

**Comment by wmonecke** [comment]
I got the same error!

`"react-native-fcm": "^13.3.3",`

**Comment by evollu** [comment]
@wmonecke you issue is most likely not integrating the library correctly, therefore RNFIRMessaging being undefined.

**Comment by vaibhavk98** [comment]
I am having same error in Android
`"react-native-fcm": "^14.0.0",
  "react-native-firebase": "^3.2.7"`

**Comment by evollu** [comment]
can you provide a public github repo that I can reproduce the issue?

**Comment by rahulFortunekit** [comment]
I got an error that is similar!
It is not working on android.
please help me

undefined is not an object (evaluating 'RNFIRMessaging.requestPermissions')

**Comment by rahulFortunekit** [comment]
this is my code for react-native with fcm plugin https://github.com/rahulFortunekit/fcmPlugin

**Comment by rahulFortunekit** [comment]
Please help me out asap
