### ISSUE TITLE
Could not invoke RNFIRMessaging.getFCMToken (Android)

### ISSUE THREAD

**Issue by nertilzhuri** [evollu/react-native-fcm#90]
Greetings,

While testing the FCM in react-native android, I got an error as the following: "Could not invoke RNFIRMessaging.getFCMToken" while trying to get the token using the sample code given in the README.

The problem might as well be with _native modules_ but I cannot find any help anywhere on google or on the _issues_ here at this project. If it is helpful the android monitor is giving the following error while running the app:

![screenshot from 2016-08-29 21-35-28](https://cloud.githubusercontent.com/assets/12595516/18064773/2a84e296-6e31-11e6-8086-a05ab7126ef5.png)

Any help is appreciated.
Thank you.

Details: 
react-native version: 0.32.0
react-native-fcm version: 1.0.16

**Comment by evollu** [comment]
it is likely that FCM is linked correctly. have you run link command?

**Comment by nertilzhuri** [comment]
Thank you for your response.

Yes I have run the link command, but I have run the 'rnpm link ...' command since the 'react-native link ...' threw errors.

Also I don't know if it is related but I removed the @Override from 'onNewIntent' function on FIRMessagingModule.java since it caused error while building the app.

Thank you

**Comment by evollu** [comment]
hm you shouldn't remove any code in the module. What is the error?

**Comment by nertilzhuri** [comment]
The error is:
error: method does not override or implement a method from a supertype 

It is the same error as in issue #69 only that all other libraies that I have installed until now work perfectly without the need to change the maven directory.

**Comment by evollu** [comment]
which version of react-native are you using?

**Comment by nertilzhuri** [comment]
react-native version: 0.32.0
react-native-fcm version: 1.0.16

I tried reinstalling the react-native-fcm on the same project but different computer, still the @Override gives error

**Comment by evollu** [comment]
let me try upgrading to rn 32

**Comment by nertilzhuri** [comment]
I fixed the problem by initializing a new react-native project and reinstalling all the libraries, it seems that either upgrading to rn 32 or linking any other library caused the problems.

I thank you for this great package and the time you spent assisting me.

**Comment by agrass** [comment]
Hi, I'm with this problem using RN 41 and 7.0.3 RNFCM. Any another solution to this??

**Comment by evollu** [comment]
@agrass on android? what error do you get?

**Comment by agrass** [comment]
Thanks for the fast response @evollu ! I'm with Android. I get this error:
```
Fatal Exception: java.lang.RuntimeException: Could not invoke RNFIRMessaging.getFCMToken
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:333)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:148)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:319)
       at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:148)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.IncompatibleClassChangeError: The method 'java.io.File android.support.v4.content.ContextCompat.getNoBackupFilesDir(android.content.Context)' was expected to be of type virtual but instead was found to be of type direct (declaration of 'com.google.firebase.iid.zzg' appears in /data/app/com.datascope-1/base.apk)
       at com.google.firebase.iid.zzg.zzeC(Unknown Source)
```

**Comment by evollu** [comment]
perhaps your module is not linked correctly. Does your MainApplication.java have new FIRMessagingPackage()?

**Comment by agrass** [comment]
yes, could be something related with firebase SDK version? I'm using 9.0.0? I need to use 10.0.1?

**Comment by evollu** [comment]
eh yeah.. can you try that

**Comment by agrass** [comment]
Thanks @evollu. Now is working. It was the version of the SDK. I was declaring ```apply plugin: 'com.google.gms.google-services' ``` above  
```
compile ("com.google.android.gms:play-services-gcm:10.0.1") {
        force = true;
    } 
```
Now changing the order is working 👍
