### ISSUE TITLE
Unable to show percentage sign in notification body

### ISSUE THREAD

**Issue by emtiajium** [evollu/react-native-fcm#944]
For example, the notification body is, `10% Interest!` I cannot show that notification body when the app is in the `foreground`. I used `FCM.presentLocalNotification()` to send the notification when the app is in the foreground. The console is showing error given below:

`failed to send local notification`
`java.lang.IllegalArgumentException: Invalid % sequence at 46: 10% Interest!`

`at libcore.net.UriCodec.decode(UriCodec.java:169)`
`at java.net.URLDecoder.decode(URLDecoder.java:60)`
`at com.evollu.react.fcm.SendNotificationTask.doInBackground(SendNotificationTask.java:63)`
`at com.evollu.react.fcm.SendNotificationTask.doInBackground(SendNotificationTask.java:37)`
`at android.os.AsyncTask$2.call(AsyncTask.java:295)`
`at java.util.concurrent.FutureTask.run(FutureTask.java:237)`
`at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)`
`at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)`
`at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)`
`at java.lang.Thread.run(Thread.java:818)`

### Environment
* react 16.3.1
* react-native 0.55.2
* react-native-fcm 14.1.3

**Comment by emtiajium** [comment]
Also, newline (`\n`) isn't working.

**Comment by emtiajium** [comment]
It works! Thank you.
