### ISSUE TITLE
simple-fcm-client crashing

### ISSUE THREAD

**Issue by sadhu05** [evollu/react-native-fcm#966]
simple-fcm-client build is successful but app is crashing.

**Comment by viethoangqe** [comment]
i have same problem here. i built with android studio 3 when start app 
```sh
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.zza" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.xxx.xxx-lBcsctKwjDfAu2-jq_KjPQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.xxx-lBcsctKwjDfAu2-jq_KjPQ==/lib/x86, /system/fake-libs, /data/app/com.xxx.xxx-lBcsctKwjDfAu2-jq_KjPQ==/base.apk!/lib/x86, /system/lib]]
06-06 20:53:31.043  4613  4647 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
06-06 20:53:31.043  4613  4647 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
06-06 20:53:31.043  4613  4647 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
06-06 20:53:31.043  4613  4647 E AndroidRuntime: 	... 14 more
``` 
```

**Comment by Shinichi52** [comment]
i have same problem here. crash message:

```sh
java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.safeparcel.zza" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.xxx.xxx-lBcsctKwjDfAu2-jq_KjPQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.xxx-lBcsctKwjDfAu2-jq_KjPQ==/lib/x86, /system/fake-libs, /data/app/com.xxx.xxx-lBcsctKwjDfAu2-jq_KjPQ==/base.apk!/lib/x86, /system/lib]]
06-06 20:53:31.043  4613  4647 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
06-06 20:53:31.043  4613  4647 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
06-06 20:53:31.043  4613  4647 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
06-06 20:53:31.043  4613  4647 E AndroidRuntime: 	... 14 more

```

**Comment by evollu** [comment]
have you included latest google SDK?

**Comment by jamesjara** [comment]
Same here
