### ISSUE TITLE
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzbq;

### ISSUE THREAD

**Issue by NarendraSingh88** [evollu/react-native-fcm#998]
```
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzbq;
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:2)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6335)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5850)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5758)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1668)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:172)
        at android.app.ActivityThread.main(ActivityThread.java:6590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzbq" on path: DexPathList[[zip file "/data/app/com.MYapp-ueUe2odQ-WU5yF60E7bQaw==/base.apk"],nativeLibraryDirectories=[/data/app/com.MYapp-ueUe2odQ-WU5yF60E7bQaw==/lib/arm, /data/app/com.MYapp-ueUe2odQ-WU5yF60E7bQaw==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:2) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6335) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5850) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5758) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1668) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:172) 
        at android.app.ActivityThread.main(ActivityThread.java:6590) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
07-11 13:45:12.660 32203-32203/? I/Process: Sending signal. PID: 32203 SIG: 9

```

**Comment by sijad** [comment]
I had same issue, after trying lots of things, this fixed this issue for me:

1. added `googlePlayServicesVersion=12.0.1` to `gradle.properties`
2. added following to `android/build.gradle`:
```gradle
 allprojects {
    repositories {
    //start here
    configurations.all {
 resolutionStrategy.eachDependency { DependencyResolveDetails details ->
   def requested = details.requested
       if (requested.group == 'com.google.android.gms') {
          details.useVersion '12.0.1'
       }
       if (requested.group == 'com.google.firebase') {
          details.useVersion '12.0.1'
         }
       }
     }
    //end
     jcenter()
       maven {
         url "https://maven.google.com"
       }
     }
 }
```

I've found this in https://github.com/idehub/react-native-google-analytics-bridge/wiki/Solution-for-Android-build-failure-issues

**Comment by herarya** [comment]
+1 same issue `""react-native-fcm": "^15.0.2",`

**Comment by ahmed7official** [comment]
@sijad lot of thanks, you made my day bro

**Comment by isnafirdasari** [comment]
thank you its work

**Comment by ferreteriaindar** [comment]
Thank you sir, its working now

**Comment by minhphung210** [comment]
@sijad  thank you <3

**Comment by saegeullee** [comment]
Thanks a lot!! It works!!

**Comment by OlivierJM** [comment]
Thanks this solved my issue.

**Comment by HanYelim** [comment]
Thank you... you are my hero... T - T

**Comment by nandgreat** [comment]
Thank you very much man... I almost gave up on the error

**Comment by jhonatansabadi** [comment]
THANK YOU VERY MUCH !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by trongnhanst94** [comment]
thanks you!

**Comment by Rajeshwari98** [comment]
Thanks a lot! I almost gave up on the app

**Comment by LogeshwariMurugan** [comment]
2018-12-13 17:40:14.599 20334-20334/com.innoart.justcopy E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.innoart.justcopy, PID: 20334
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/Api$zzf;
        at com.google.android.gms.auth.api.Auth.<clinit>(Unknown Source:0)
        at com.innoart.justcopy.GoogleSignIn.onCreate(GoogleSignIn.java:41)
        at android.app.Activity.performCreate(Activity.java:7032)
        at android.app.Activity.performCreate(Activity.java:7023)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1236)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2814)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.Api$zzf" on path: DexPathList[[zip file "/data/app/com.innoart.justcopy-qG1SGsDM4a_ERbLCqGzEXQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.innoart.justcopy-qG1SGsDM4a_ERbLCqGzEXQ==/lib/arm, /data/app/com.innoart.justcopy-qG1SGsDM4a_ERbLCqGzEXQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.android.gms.auth.api.Auth.<clinit>(Unknown Source:0) 
        at com.innoart.justcopy.GoogleSignIn.onCreate(GoogleSignIn.java:41) 
        at android.app.Activity.performCreate(Activity.java:7032) 
        at android.app.Activity.performCreate(Activity.java:7023) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1236) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2814) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6626) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

**Comment by MSSPL-PiyaleeMaiti** [comment]
@sijad Thanks for the solution. It work's for me.

**Comment by satyendrababu** [comment]
Thank buddy. It's working for me...

**Comment by matiasvilches** [comment]
¡Muchas gracias!

**Comment by uday-brainium** [comment]
@sijad  Thanks it works for me also .

**Comment by nadeem362** [comment]
Thanks, it saved my day.........

**Comment by jamienjoroge** [comment]
> 
> 
> I had same issue, after trying lots of things, this fixed this issue for me:
> 
>     1. added `googlePlayServicesVersion=12.0.1` to `gradle.properties` (I guess it's unnecessary)
> 
>     2. added following to `android/build.gradle`:
> 
> 
> ```groovy-gradle
>  allprojects {
>     repositories {
>     //start here
>     configurations.all {
>  resolutionStrategy.eachDependency { DependencyResolveDetails details ->
>    def requested = details.requested
>        if (requested.group == 'com.google.android.gms') {
>           details.useVersion '12.0.1'
>        }
>        if (requested.group == 'com.google.firebase') {
>           details.useVersion '12.0.1'
>          }
>        }
>      }
>     //end
>      jcenter()
>        maven {
>          url "https://maven.google.com"
>        }
>      }
>  }
> ```
> 
> I've found this in https://github.com/idehub/react-native-google-analytics-bridge/wiki/Solution-for-Android-build-failure-issues

worked like a charm. thanks

**Comment by zeeshanarif573** [comment]
@sijad you have saved a lot of time bro.. thanks its working.. :)

**Comment by eraydemirok** [comment]
@sijad it worked, thanks!

**Comment by Mallan240292** [comment]
@sijad Thanks a lot, worked...

**Comment by thanhnh98** [comment]
thanks , it worked <3

**Comment by lakshmanbodduluru** [comment]
Thanks a lot, it's resolved

**Comment by jirawutch** [comment]
it worked thank alot.

**Comment by ashwithraja** [comment]
It works fine in debug and giving build error on enabling the release by enabling the progaurd. any specific reason for this

**Comment by Saurabhreactninja** [comment]
thanks @sijad worked like a piece of cake .

**Comment by BezMan** [comment]
worked for me, crazy thanks!

**Comment by nugrohosan** [comment]
thanks brother

**Comment by amitanshu-brandmaker** [comment]
Thanks alot. 
Wasted alot of time finally got this answer and it worked like a charm.

**Comment by fuengfa** [comment]
Thank you so much.

**Comment by boerkey** [comment]
Worked for me in RN 0.60.5 as well, thanks mate!

**Comment by dewmalFernando** [comment]
Thank you so much. Works for me

**Comment by rajeshsmallarc** [comment]
@sijad Thank you so much. Works for me

**Comment by CoderJWYang** [comment]
Thank you so much. Works for me

**Comment by voltsoftdev** [comment]
A lot thanks !! your kindness help me resolve my issue !

**Comment by kigh143** [comment]
thanks @sijad it works fine for me

**Comment by MahefaAbel** [comment]
@sijad > thanks, it's work

**Comment by KhaoulaElmajni** [comment]
thank you soooo much brother it's working ^^

**Comment by MianJawadAhmad** [comment]
> I had same issue, after trying lots of things, this fixed this issue for me:
> 
> 1. added `googlePlayServicesVersion=12.0.1` to `gradle.properties` (I guess it's unnecessary)
> 2. added following to `android/build.gradle`:
> 
> ```groovy-gradle
>  allprojects {
>     repositories {
>     //start here
>     configurations.all {
>  resolutionStrategy.eachDependency { DependencyResolveDetails details ->
>    def requested = details.requested
>        if (requested.group == 'com.google.android.gms') {
>           details.useVersion '12.0.1'
>        }
>        if (requested.group == 'com.google.firebase') {
>           details.useVersion '12.0.1'
>          }
>        }
>      }
>     //end
>      jcenter()
>        maven {
>          url "https://maven.google.com"
>        }
>      }
>  }
> ```
> 
> I've found this in https://github.com/idehub/react-native-google-analytics-bridge/wiki/Solution-for-Android-build-failure-issues

thank you so much bro

**Comment by BrilliantHK** [comment]
thanks!

**Comment by ElonMuskPro** [comment]
this is magic, you're the best

**Comment by hoangtuanitstar** [comment]
If we want to use a higher version, how can I do, please ?

**Comment by MarcelaRotaru** [comment]
> I had same issue, after trying lots of things, this fixed this issue for me:
> 
> 1. added `googlePlayServicesVersion=12.0.1` to `gradle.properties` (I guess it's unnecessary)
> 2. added following to `android/build.gradle`:
> 
> ```groovy-gradle
>  allprojects {
>     repositories {
>     //start here
>     configurations.all {
>  resolutionStrategy.eachDependency { DependencyResolveDetails details ->
>    def requested = details.requested
>        if (requested.group == 'com.google.android.gms') {
>           details.useVersion '12.0.1'
>        }
>        if (requested.group == 'com.google.firebase') {
>           details.useVersion '12.0.1'
>          }
>        }
>      }
>     //end
>      jcenter()
>        maven {
>          url "https://maven.google.com"
>        }
>      }
>  }
> ```
> 
> I've found this in https://github.com/idehub/react-native-google-analytics-bridge/wiki/Solution-for-Android-build-failure-issues

Thank you very much! It works :)

**Comment by AlexandreLage** [comment]
Obrigado!

**Comment by geraldPhiri** [comment]
Thanks bro you saved me

**Comment by phasapt** [comment]
@sijad you save me!! Thanks!!!

**Comment by SciaticNutria85** [comment]
Thank u so much bro, you have saved my life

**Comment by redapple1990** [comment]
Thank you very much. you rule!

**Comment by NehaKushwah993** [comment]
Worked for me Thanks!

**Comment by hugoh59** [comment]
Still working in 2020, thank you!

**Comment by ash110298** [comment]
thank you so much its works for me

**Comment by Paul-Lategan** [comment]
Thank you very much, working for me in Feb 2021.

**Comment by alex-shamshurin** [comment]
Actual is here https://github.com/idehub/react-native-google-analytics-bridge/wiki/Android-build-problems

**Comment by sohanpc** [comment]
> I had same issue, after trying lots of things, this fixed this issue for me:
> 
> 1. added `googlePlayServicesVersion=12.0.1` to `gradle.properties` (I guess it's unnecessary)
> 2. added following to `android/build.gradle`:
> 
> ```groovy-gradle
>  allprojects {
>     repositories {
>     //start here
>     configurations.all {
>  resolutionStrategy.eachDependency { DependencyResolveDetails details ->
>    def requested = details.requested
>        if (requested.group == 'com.google.android.gms') {
>           details.useVersion '12.0.1'
>        }
>        if (requested.group == 'com.google.firebase') {
>           details.useVersion '12.0.1'
>          }
>        }
>      }
>     //end
>      jcenter()
>        maven {
>          url "https://maven.google.com"
>        }
>      }
>  }
> ```
> 
> I've found this in https://github.com/idehub/react-native-google-analytics-bridge/wiki/Solution-for-Android-build-failure-issues

You are saving my time: the same issue was in the Ionic https://ionicframework.com/docs/native/location-accuracy with https://ionicframework.com/docs/native/admob-free

Thanks @sijad :)

**Comment by MadhavNimavat** [comment]
> I had same issue, after trying lots of things, this fixed this issue for me:
> 
> 1. added `googlePlayServicesVersion=12.0.1` to `gradle.properties` (I guess it's unnecessary)
> 2. added following to `android/build.gradle`:
> 
> ```groovy-gradle
>  allprojects {
>     repositories {
>     //start here
>     configurations.all {
>  resolutionStrategy.eachDependency { DependencyResolveDetails details ->
>    def requested = details.requested
>        if (requested.group == 'com.google.android.gms') {
>           details.useVersion '12.0.1'
>        }
>        if (requested.group == 'com.google.firebase') {
>           details.useVersion '12.0.1'
>          }
>        }
>      }
>     //end
>      jcenter()
>        maven {
>          url "https://maven.google.com"
>        }
>      }
>  }
> ```
> 
> I've found this in https://github.com/idehub/react-native-google-analytics-bridge/wiki/Solution-for-Android-build-failure-issues

You're great buddy saved me
